### ISSUE TITLE
Update interval-arithmetic to support Euler's constant

### ISSUE THREAD

**Issue by hieuthi** [mauriciopoppe/interval-arithmetic-eval#8]
Hello,
I saw that you have add support for Euler's constant in https://github.com/mauriciopoppe/interval-arithmetic 
Can you update the dependence to downstream so it can be used within https://github.com/mauriciopoppe/function-plot

**Comment by mauriciopoppe** [comment]
Release [v1.23.0](https://github.com/mauriciopoppe/function-plot/releases/tag/v1.23.0) of function-plot has the constant available.
