### ISSUE TITLE
Still not able to use Euler's constant

### ISSUE THREAD

**Issue by hieuthi** [mauriciopoppe/interval-arithmetic-eval#9]
I tested the latest version of function-plot and this library but neither can use Euler's constant (#8)
I check the the latest version of interval-arithmetic (v1.1.0) at npm and found out there is no trace of E in the source code https://registry.npmjs.org/interval-arithmetic/-/interval-arithmetic-v1.1.0.tgz

I think you may have published the old version of interval-arithmetic (the one without E) to npm but used the new version tag.

**Comment by mauriciopoppe** [comment]
Thanks for the catching it and sorry for the late response. I released a new version of interval-arithmetic and used in https://github.com/mauriciopoppe/function-plot/releases/tag/v1.23.1 which should have it.
